- @stellar/design-system-website/public/index.html
- @stellar/design-system-website/src/components/Details/index.tsx
- @stellar/design-system-website/src/components/Details/styles.scss
- @stellar/design-system-website/src/pages/Landing.tsx
- @stellar/design-system-website/src/styles.scss
- @stellar/design-system/src/global.scss
The website should be somewhat presentable. 🤞 😅
> Website UI polishes

- @stellar/design-system-website/package.json
- @stellar/design-system-website/src/App.tsx
- @stellar/design-system-website/src/components/Details/styles.scss
- @stellar/design-system/src/components/Button/styles.scss
- @stellar/design-system/src/components/Identicon/styles.scss
- @stellar/design-system/src/components/InfoBlock/index.tsx
- @stellar/design-system/src/components/InfoBlock/styles.scss
- @stellar/design-system/src/components/TextLink/styles.scss
- @stellar/design-system/src/components/ToggleDarkMode/index.tsx
- @stellar/design-system/src/components/ToggleDarkMode/styles.scss
- @stellar/design-system/src/components/utils/FieldElement/index.tsx
- @stellar/design-system/src/global.scss
- @stellar/design-system/src/mixins.scss
Note: Small design/color tweaks (missing hover states, etc.) will be addressed after QA.
> Color palette updates + small tweaks

- @stellar/design-system-website/src/constants/componentDetails.ts
- @stellar/design-system-website/src/constants/componentsInDisplayOrder.ts
- @stellar/design-system-website/src/constants/details/tags.tsx
- @stellar/design-system-website/src/types/types.d.ts
- @stellar/design-system/src/components/NavButton/index.tsx
- @stellar/design-system/src/components/Tag/index.tsx
- @stellar/design-system/src/components/Tag/styles.scss
- @stellar/design-system/src/components/index.ts
> Tag component

- .circleci/config.yml
- @stellar/design-system-website/package.json
- @stellar/design-system/package.json
- @stellar/design-system/src/components/Layout/index.tsx
- @stellar/design-system/src/components/ToggleDarkMode/index.tsx
- @stellar/design-system/src/global.scss
- package.json
- Set light mode by default if the theme toggle component is not on the website
- Update `code` style to use `em` instead `rem` for size attributes
- Update CircleCI script to publish npm package
> Release v0.2.1

- @stellar/design-system-website/package.json
- @stellar/design-system-website/src/App.tsx
- @stellar/design-system-website/src/components/SideNav/index.tsx
- @stellar/design-system-website/src/components/SideNav/styles.scss
- @stellar/design-system-website/src/constants/variables.ts
- @stellar/design-system-website/src/generated/gitInfo.ts
- @stellar/design-system-website/src/pages/Landing.tsx
- @stellar/design-system-website/src/styles.scss
- yarn.lock
- Move some constants to separate file
- Make side navigation sticky
- Added `lodash`
> Sticky side nav

- .circleci/config.yml
- @stellar/design-system-website/package.json
- @stellar/design-system-website/src/constants/details/layout.tsx
- @stellar/design-system-website/src/generated/gitInfo.ts
- @stellar/design-system/package.json
- @stellar/design-system/src/components/Layout/index.tsx
- @stellar/design-system/src/components/Layout/styles.scss
- @stellar/design-system/src/components/ToggleDarkMode/index.tsx
- Layout Header component updates:
- Add sign out link
- Add option to add a border around navigation buttons
- Update npm publish script
- Update SDS version to 0.2.2
> Layout header updates

- @stellar/design-system-website/package.json
- @stellar/design-system-website/src/constants/details/layout.tsx
- @stellar/design-system-website/src/generated/gitInfo.ts
- @stellar/design-system/package.json
- @stellar/design-system/src/components/Layout/index.tsx
- @stellar/design-system/src/components/TextLink/styles.scss
- @stellar/design-system/src/components/ToggleDarkMode/index.tsx
- @stellar/design-system/src/global.scss
- Don't change color on `TextLink` when underlined
- Update default animation variable `--anim-transition-default`
- Add `onDarkModeToggleEnd()` to `Layout.Header`
> Small updates

- @stellar/design-system-website/package.json
- @stellar/design-system-website/src/constants/componentDetails.ts
- @stellar/design-system-website/src/constants/componentsInDisplayOrder.ts
- @stellar/design-system-website/src/constants/details/copyTexts.tsx
- @stellar/design-system-website/src/constants/details/detailsTooltips.tsx
- @stellar/design-system-website/src/constants/details/statusBars.tsx
- @stellar/design-system-website/src/constants/details/tooltips.tsx
- @stellar/design-system-website/src/generated/gitInfo.ts
- @stellar/design-system-website/src/types/types.d.ts
- @stellar/design-system/package.json
- @stellar/design-system/src/components/CopyText/index.tsx
- @stellar/design-system/src/components/CopyText/styles.scss
- @stellar/design-system/src/components/DetailsTooltip/index.tsx
- @stellar/design-system/src/components/DetailsTooltip/styles.scss
- @stellar/design-system/src/components/Layout/index.tsx
- @stellar/design-system/src/components/Layout/styles.scss
- @stellar/design-system/src/components/Modal/styles.scss
- @stellar/design-system/src/components/Select/styles.scss
- @stellar/design-system/src/components/StatusBar/index.tsx
- @stellar/design-system/src/components/StatusBar/styles.scss
- @stellar/design-system/src/components/Tooltip/index.tsx
- @stellar/design-system/src/components/Tooltip/styles.scss
- @stellar/design-system/src/components/index.ts
- @stellar/design-system/src/global.scss
- yarn.lock
New components:
- `StatusBar`
- `Tooltip`
- `DetailsTooltip`
- `CopyText`
Fixes:
- Align footer children to the right (instead of the middle)
- Make headings in modals one step smaller
- Fix dropdown arrow alignment on `Select`
- Remove `overflow-x: hidden` from `body` and `#root`
- Fix button spacing in `Modal` footer
> New components + UI tweaks

- @stellar/design-system-website/package.json
- @stellar/design-system-website/src/generated/gitInfo.ts
- @stellar/design-system/package.json
- @stellar/design-system/src/global.scss
Updated palette dark theme text colors.
> Release 0.4.2

- @stellar/design-system-website/src/constants/details/checkboxes.tsx
- @stellar/design-system-website/src/generated/gitInfo.ts
- @stellar/design-system/src/components/Checkbox/index.tsx
- @stellar/design-system/src/components/Checkbox/styles.scss
> Checkbox: add note and error

- @stellar/design-system-website/src/constants/details/toggles.tsx
- @stellar/design-system-website/src/generated/gitInfo.ts
> Toggle: settings example

- @stellar/design-system-website/src/constants/componentDetails.ts
- @stellar/design-system-website/src/constants/componentsInDisplayOrder.ts
- @stellar/design-system-website/src/constants/details/mocks.tsx
- @stellar/design-system-website/src/constants/details/textareas.tsx
- @stellar/design-system-website/src/generated/gitInfo.ts
- @stellar/design-system-website/src/types/types.d.ts
- @stellar/design-system/src/components/Textarea/index.tsx
- @stellar/design-system/src/components/Textarea/styles.scss
- @stellar/design-system/src/components/index.ts
> Textarea component

- @stellar/design-system-website/src/constants/details/inputs.tsx
- @stellar/design-system-website/src/generated/gitInfo.ts
- @stellar/design-system/src/components/Checkbox/index.tsx
- @stellar/design-system/src/components/Input/index.tsx
- @stellar/design-system/src/components/Input/styles.scss
- @stellar/design-system/src/components/Label/index.tsx
- @stellar/design-system/src/components/Label/styles.scss
- @stellar/design-system/src/components/Select/index.tsx
- @stellar/design-system/src/components/Textarea/index.tsx
- @stellar/design-system/src/components/utils/FieldNote/index.tsx
- @stellar/design-system/src/components/utils/FieldNote/styles.scss
- @stellar/design-system/src/global.scss
- Updated helper components to match new designs (other form components will be updated later).
- Updated some global styles to apply only to SDS and not generic elements.
> Updated Input component

- @stellar/design-system-website/src/constants/details/buttons.tsx
- @stellar/design-system-website/src/constants/details/cards.tsx
- @stellar/design-system-website/src/constants/details/inputs.tsx
- @stellar/design-system-website/src/generated/gitInfo.ts
- @stellar/design-system-website/src/styles.scss
- @stellar/design-system/src/components/Button/index.tsx
- @stellar/design-system/src/components/Button/styles.scss
- @stellar/design-system/src/components/Card/index.tsx
- @stellar/design-system/src/components/Card/styles.scss
- @stellar/design-system/src/components/Input/index.tsx
- @stellar/design-system/src/components/Input/styles.scss
- @stellar/design-system/src/components/Link/styles.scss
- @stellar/design-system/src/components/Typography/styles.scss
- @stellar/design-system/src/global.scss
- @stellar/design-system/src/theme.scss
- Updated `Card` component
- Added `isPill` prop to `Button` and `Input`
- Added `isExtraPadding` prop to `Button`
- Small tweaks
> Updated Card, Input, and Button components + small tweaks

- @stellar/design-system-website/src/constants/details/selects.tsx
- @stellar/design-system-website/src/generated/gitInfo.ts
- @stellar/design-system/src/components/Select/index.tsx
- @stellar/design-system/src/components/Select/styles.scss
> Updated Select component

- @stellar/design-system-website/src/constants/details/buttons.tsx
- @stellar/design-system-website/src/generated/gitInfo.ts
- @stellar/design-system/src/components/Button/index.tsx
- @stellar/design-system/src/components/Button/styles.scss
> Button: destructive/error/success variants

- @stellar/design-system-website/src/constants/details/modals.tsx
- @stellar/design-system-website/src/generated/gitInfo.ts
- @stellar/design-system/src/components/Modal/index.tsx
- @stellar/design-system/src/components/Modal/styles.scss
Can align to the bottom on small screens
> Updated Modal component

- @stellar/design-system-website/src/constants/details/inputs.tsx
- @stellar/design-system-website/src/generated/gitInfo.ts
- @stellar/design-system/src/components/Input/index.tsx
- @stellar/design-system/src/components/Input/styles.scss
> Input password

- @stellar/design-system-website/docs/components/buttons/link.mdx
- @stellar/design-system-website/src/componentPreview/buttonPreview.tsx
- @stellar/design-system-website/src/componentPreview/linkPreview.tsx
- @stellar/design-system-website/src/components/PreviewBlock/index.tsx
- @stellar/design-system-website/src/components/PreviewBlock/styles.css
> Component preview: Link

- @stellar/design-system-website/docs/components/branding/_category_.json
- @stellar/design-system-website/docs/components/branding/project-logo.mdx
- @stellar/design-system-website/src/componentPreview/projectLogoPreview.tsx
- @stellar/design-system-website/src/components/ComponentProps/index.tsx
- @stellar/design-system-website/src/components/PreviewBlock/index.tsx
- @stellar/design-system-website/src/css/custom.css
- @stellar/design-system/src/components/ProjectLogo/index.tsx
> ProjectLogo preview

- @stellar/design-system-website/docs/components/notifications/_category_.json
- @stellar/design-system-website/docs/components/notifications/notification.mdx
- @stellar/design-system-website/src/componentPreview/notificationPreview .tsx
- @stellar/design-system-website/src/components/PreviewBlock/index.tsx
- @stellar/design-system/src/components/Notification/index.tsx
- @stellar/design-system/src/components/Notification/styles.scss
> Notification docs + preview

- @stellar/design-system-website/docs/components/elements/_category_.json
- @stellar/design-system-website/docs/components/elements/avatar.mdx
- @stellar/design-system-website/src/componentPreview/avatarPreview.tsx
- @stellar/design-system-website/src/components/PreviewBlock/index.tsx
- @stellar/design-system/src/components/Avatar/index.tsx
> Avatar docs + preview

- @stellar/design-system-website/docs/components/accents/_category_.json
- @stellar/design-system-website/docs/components/accents/badge.mdx
- @stellar/design-system-website/src/componentPreview/badgePreview.tsx
- @stellar/design-system-website/src/components/PreviewBlock/index.tsx
- @stellar/design-system/src/components/Badge/index.tsx
> Badge docs + preview

- @stellar/design-system-website/docs/components/profile/_category_.json
- @stellar/design-system-website/docs/components/profile/profile.mdx
- @stellar/design-system-website/src/componentPreview/profilePreview.tsx
- @stellar/design-system-website/src/components/ComponentProps/index.tsx
- @stellar/design-system-website/src/components/ElementPropType.tsx
- @stellar/design-system-website/src/components/ParseSummary.tsx
- @stellar/design-system-website/src/components/PreviewBlock/index.tsx
- @stellar/design-system-website/src/components/PreviewBlock/styles.css
- @stellar/design-system/src/components/Profile/index.tsx
> Profile docs + preview

- @stellar/design-system-website/docs/components/elements/loader.mdx
- @stellar/design-system-website/src/componentPreview/loaderPreview.tsx
- @stellar/design-system-website/src/components/PreviewBlock/index.tsx
- @stellar/design-system/src/components/Loader/index.tsx
> Loader docs + preview

- @stellar/design-system-website/docs/components/inputs/_category_.json
- @stellar/design-system-website/docs/components/inputs/input.mdx
- @stellar/design-system-website/src/componentPreview/inputPreview.tsx
- @stellar/design-system-website/src/components/PreviewBlock/index.tsx
- @stellar/design-system-website/src/components/PreviewBlock/styles.css
- @stellar/design-system/src/components/Input/index.tsx
> Input docs + preview

- @stellar/design-system-website/docs/components/inputs/_category_.json
- @stellar/design-system-website/docs/components/inputs/checkbox.mdx
- @stellar/design-system-website/src/componentPreview/checkboxPreview.tsx
- @stellar/design-system-website/src/components/PreviewBlock/index.tsx
- @stellar/design-system/src/components/Checkbox/index.tsx
> Checkbox docs + preview

- @stellar/design-system-website/docs/components/layout/table.mdx
- @stellar/design-system-website/src/componentPreview/tablePreview.tsx
- @stellar/design-system-website/src/components/ElementPropType.tsx
- @stellar/design-system-website/src/components/PreviewBlock/index.tsx
- @stellar/design-system-website/src/components/PreviewBlock/styles.css
- @stellar/design-system/src/components/Table/index.tsx
> Table docs + preview

- @stellar/design-system/package.json
- @stellar/design-system/src/components/Floater/index.tsx
- Dockerfile
- yarn.lock
This update should fix the below React key warning when running the app in developer mode.
> Fix Tooltip React key warning + upgrade floating-ui/dom

- @stellar/design-system-website/docs/components/notifications/alert.mdx
- @stellar/design-system-website/src/componentPreview/alertPreview.tsx
- @stellar/design-system-website/src/componentPreview/linkPreview.tsx
- @stellar/design-system-website/src/components/ComponentDescription/index.tsx
- @stellar/design-system-website/src/components/PreviewBlock/index.tsx
- @stellar/design-system/src/components/Alert/index.tsx
- @stellar/design-system/src/components/Alert/styles.scss
- @stellar/design-system/src/components/ButtonPreset/index.tsx
- @stellar/design-system/src/components/CopyText/index.tsx
- @stellar/design-system/src/components/IconButton/index.tsx
- @stellar/design-system/src/components/Link/index.tsx
- @stellar/design-system/src/components/Link/styles.scss
- @stellar/design-system/src/components/Modal/index.tsx
- @stellar/design-system/src/components/NavButton/index.tsx
- @stellar/design-system/src/components/Table/index.tsx
- @stellar/design-system/src/components/Typography/styles.scss
- @stellar/design-system/src/components/index.ts
- Added new `Alert` component
- Added `success`, `warning`, and `error` variants to the `Link` component
- Some cleanup
> V3 Alert + new variants for Link

- @stellar/design-system-website/docs/foundations/typography/text.mdx
- @stellar/design-system-website/src/componentPreview/textPreview.tsx
- @stellar/design-system-website/src/components/PreviewBlock/styles.css
- @stellar/design-system/src/components/Typography/index.tsx
- @stellar/design-system/src/components/Typography/styles.scss
There are cases where we need `Text` styled headings. This update adds support for that.
> V3 Update Text component

- @stellar/design-system-website/src/componentPreview/inputPreview.tsx
- @stellar/design-system-website/src/componentPreview/selectPreview.tsx
- @stellar/design-system-website/src/componentPreview/textareaPreview.tsx
- @stellar/design-system/src/components/Input/index.tsx
- @stellar/design-system/src/components/Label/index.tsx
- @stellar/design-system/src/components/Label/styles.scss
- @stellar/design-system/src/components/Select/index.tsx
- @stellar/design-system/src/components/Textarea/index.tsx
Add a suffix to the label (optional, required, or any other text).
> Add Label suffix

- @stellar/design-system-website/docs/components/containers/modal.mdx
- @stellar/design-system-website/src/components/PreviewBlock/index.tsx
- @stellar/design-system/src/components/Modal/styles.scss
Small adjustments to margin/padding and title font size.
> V3 Update Modal

- @stellar/design-system/src/components/Alert/index.tsx
- @stellar/design-system/src/components/Alert/styles.scss
- @stellar/design-system/src/components/Button/index.tsx
- @stellar/design-system/src/components/Button/styles.scss
- @stellar/design-system/src/components/Floater/index.tsx
- @stellar/design-system/src/components/Select/styles.scss
- Update Select outline and border
**Before**
**After**
- Alert: custom icon + fix title letter spacing
**Before**
**After**
- Button: onClick action tooltip
**Before**
[sds-button-tooltip-before.webm](https://github.com/user-attachments/assets/dd1ded61-be87-4e23-b3ad-ddeb2b60e176)
**After**
[sds-button-tooltip-after.webm](https://github.com/user-attachments/assets/2463aa82-fb36-43c5-bc70-a2eff2b7e0b4)
- Floater: fix tooltip arrow position if placement is flipped automatically
**Before**
**After**
> Update Alert + Button + Floater

- .github/workflows/codeql.yml
- @stellar/design-system-website/package.json
- @stellar/design-system/package.json
- Merged `main` branch
- Updated package version to `3.0.0`
> Prep for v3 launch

- @stellar/design-system-website/package.json
- @stellar/design-system-website/src/componentPreview/buttonPreview.tsx
- @stellar/design-system/package.json
- @stellar/design-system/src/components/Button/index.tsx
- @stellar/design-system/src/components/Button/styles.scss
> Button: add XL size
