stellar/stellar-design-system

- @stellar/design-system-website/src/generated/gitInfo.ts
- @stellar/design-system/src/components/InfoBlock/index.tsx
- @stellar/design-system/src/components/InfoBlock/styles.scss
- @stellar/design-system/src/components/StatusBar/index.tsx
- @stellar/design-system/src/components/StatusBar/styles.scss
- @stellar/design-system/src/components/Tag/styles.scss
- @stellar/design-system/src/components/Tooltip/styles.scss
- @stellar/design-system/src/global.scss
Replacing RGBA colors with solid colors to make sure colors are eligible in every scenario. This update should not break anything unless `-rgb` colors are used directly in local projects.
Updated components (colors + some cleanup):
- `InfoBlock`
- `StatusBar`
- `Tag`
- `Tooltip`
> Replace RGBA colors with solid colors

- @stellar/design-system-website/src/constants/details/buttons.tsx
- @stellar/design-system-website/src/generated/gitInfo.ts
- @stellar/design-system/src/components/Button/index.tsx
- @stellar/design-system/src/components/Button/styles.scss
- @stellar/design-system/src/components/Layout/index.tsx
- @stellar/design-system/src/components/TextLink/index.tsx
- Add optional `size` prop to Button component (default size did not change).
- Small cleanup
> Button small size + cleanup

- @stellar/design-system-website/src/constants/details/inputs.tsx
- @stellar/design-system-website/src/constants/details/selects.tsx
- @stellar/design-system-website/src/constants/details/tables.tsx
- @stellar/design-system-website/src/generated/gitInfo.ts
- @stellar/design-system/src/components/Input/index.tsx
- @stellar/design-system/src/components/Select/index.tsx
- @stellar/design-system/src/components/Table/index.tsx
- @stellar/design-system/src/components/Tooltip/index.tsx
- @stellar/design-system/src/components/Tooltip/styles.scss
- Add optional `id` prop to Table component, used when multiple Table components are on the same page.
- Fix Tooltip overlapping bug (https://github.com/stellar/stellar-design-system/issues/86)
- Input and Select component labels can be `ReactNode` (not just strings) (https://github.com/stellar/stellar-design-system/issues/87)
> Tweaks and fixes

- @stellar/design-system-website/src/components/Details/styles.scss
- @stellar/design-system-website/src/constants/details/tables.tsx
- @stellar/design-system-website/src/generated/gitInfo.ts
- @stellar/design-system/src/components/Table/index.tsx
- @stellar/design-system/src/components/Table/styles.scss
Breaking change:
- Table requires prop `breakpoint`, used to trigger the sticky column layout.
> Table: add breakpoint

- @stellar/design-system-website/src/constants/details/copyTexts.tsx
- @stellar/design-system-website/src/constants/details/iconButtons.tsx
- @stellar/design-system-website/src/generated/gitInfo.ts
- @stellar/design-system/src/components/CopyText/index.tsx
- @stellar/design-system/src/components/CopyText/styles.scss
- @stellar/design-system/src/components/IconButton/index.tsx
- @stellar/design-system/src/components/IconButton/styles.scss
**Updates**:
- `IconButton` has new props: `label` and `preset`.
**Breaking changes**:
- `CopyText` prop `showCopyIcon` was removed, need to pass `IconButton` copy preset as children to achieve the same result.
> IconButton + CopyText updates

- .github/workflows/update_deps.yml
- @stellar/design-system-website/package.json
- @stellar/design-system-website/src/components/Details/styles.scss
- @stellar/design-system-website/src/constants/componentDetails.ts
- @stellar/design-system-website/src/constants/componentsInDisplayOrder.ts
- @stellar/design-system-website/src/constants/details/checkboxes.tsx
- @stellar/design-system-website/src/constants/details/copyTexts.tsx
- @stellar/design-system-website/src/constants/details/iconButtons.tsx
- @stellar/design-system-website/src/constants/details/mocks.tsx
- @stellar/design-system-website/src/constants/details/tables.tsx
- @stellar/design-system-website/src/constants/details/textareas.tsx
- @stellar/design-system-website/src/constants/details/toggles.tsx
- @stellar/design-system-website/src/generated/gitInfo.ts
- @stellar/design-system-website/src/types/types.d.ts
- @stellar/design-system/package.json
- @stellar/design-system/src/components/Checkbox/index.tsx
- @stellar/design-system/src/components/Checkbox/styles.scss
- @stellar/design-system/src/components/CopyText/index.tsx
- @stellar/design-system/src/components/CopyText/styles.scss
- @stellar/design-system/src/components/IconButton/index.tsx
- @stellar/design-system/src/components/IconButton/styles.scss
- @stellar/design-system/src/components/Table/index.tsx
- @stellar/design-system/src/components/Table/styles.scss
- @stellar/design-system/src/components/Textarea/index.tsx
- @stellar/design-system/src/components/Textarea/styles.scss
- @stellar/design-system/src/components/index.ts
**Breaking changes**
- Table requires a `breakpoint` property, which is used to trigger the sticky column layout.
- `CopyText` property `showCopyIcon` was removed, now you need to pass `IconButton` copy preset as `children` to achieve the same result.
**Updates**
- `IconButton` has new properties: `label` and `preset`.
- `Checkbox` has new properties: `note` and `error`.
- `Toggle` component has an example of how to use it with form labels.
- New `Textarea` component.
**Internal**
- Updated GitHub Action to update dependencies.
> Release 0.8.0

- @stellar/design-system-website/src/generated/gitInfo.ts
- @stellar/design-system/package.json
- @stellar/design-system/src/components/Avatar/index.tsx
- @stellar/design-system/src/helpers/createStellarIdenticon.js
- @stellar/design-system/src/types/@modules.d.ts
- yarn.lock
`stellar-identicon-js` uses old Webpack configuration, and some of the outdated packages have critical vulnerabilities (`json5` and `loader-utils` old versions). Serving the JS file locally should resolve that.
> Serve stellar-identicon-js locally

- @stellar/design-system-website/src/constants/details/tooltips.tsx
- @stellar/design-system-website/src/generated/gitInfo.ts
- @stellar/design-system/src/components/Floater/index.tsx
- @stellar/design-system/src/components/Floater/styles.scss
- @stellar/design-system/src/components/Tooltip/index.tsx
- @stellar/design-system/src/components/Tooltip/styles.scss
- Use a contrasting color for Floaters and Tooltip by default, with an option to change it.
- Apply Floater fix from SDP.
> Floater and tooltip color update and small fix

- @stellar/design-system/src/components/Typography/index.tsx
Right now in Typography, each component can take a `className` prop to add new classes to the base set.
If you try to pass a prop named `className` to a React component, it will treat it as the built in `className` property and will override the classes that come with the component initially.
Example - 
```
<Caption size="xs" className="step-count">
...
</Caption>
```
will result in
```
<div class="step-count">...</div>
```
and will be missing the original classes for the component, should end up being this
```
<div class="Caption Caption--xs step-count">...</div>
```
We can rename the class used to add more classes to the components class list in order to avoid this.
> rename classNames prop to addlClassName

- @stellar/design-system-website/src/constants/details/typography.tsx
- @stellar/design-system/src/components/Typography/index.tsx
I forgot to pick out `addlClassName` when adding it so React warns that it is not a known native property, this picks it out of props before spreading props onto to the dom nodes.
> picks out addlClassName from props before spreading onto dom nodes

- @stellar/design-system-website/docs/foundations/typography.mdx
- @stellar/design-system-website/docs/foundations/typography/_category_.json
- @stellar/design-system-website/docs/foundations/typography/caption.mdx
- @stellar/design-system-website/docs/foundations/typography/heading.mdx
- @stellar/design-system-website/docs/foundations/typography/paragraph.mdx
- @stellar/design-system-website/docs/foundations/typography/title.mdx
- @stellar/design-system-website/src/componentPreview/captionPreview.tsx
- @stellar/design-system-website/src/componentPreview/headingPreview.tsx
- @stellar/design-system-website/src/componentPreview/paragraphPreview.tsx
- @stellar/design-system-website/src/componentPreview/titlePreview.tsx
- @stellar/design-system-website/src/components/PreviewBlock/index.tsx
- @stellar/design-system-website/src/components/PreviewBlock/styles.css
- @stellar/design-system/src/components/Typography/index.tsx
- @stellar/design-system/src/components/Typography/styles.scss
> Typography docs + preview

- @stellar/design-system-website/docs/components/elements/asset-icon.mdx
- @stellar/design-system-website/src/componentPreview/assetIconPreview.tsx
- @stellar/design-system-website/src/components/ComponentProps/index.tsx
- @stellar/design-system-website/src/components/ElementPropType.tsx
- @stellar/design-system-website/src/components/PreviewBlock/index.tsx
- @stellar/design-system/src/components/AssetIcon/index.tsx
> AssetIcon docs + preview

- @stellar/design-system-website/docs/components/accents/tooltip.mdx
- @stellar/design-system-website/src/componentPreview/tooltipPreview.tsx
- @stellar/design-system-website/src/components/PreviewBlock/index.tsx
- @stellar/design-system/src/components/Tooltip/index.tsx
> Tooltip docs + preview

- @stellar/design-system-website/docs/components/inputs/_category_.json
- @stellar/design-system-website/docs/components/inputs/select.mdx
- @stellar/design-system-website/src/componentPreview/selectPreview.tsx
- @stellar/design-system-website/src/components/PreviewBlock/index.tsx
- @stellar/design-system-website/src/components/PreviewBlock/styles.css
- @stellar/design-system/src/components/Select/index.tsx
> Select docs + preview

- @stellar/design-system-website/docs/components/inputs/_category_.json
- @stellar/design-system-website/docs/components/inputs/textarea.mdx
- @stellar/design-system-website/src/componentPreview/textareaPreview.tsx
- @stellar/design-system-website/src/components/PreviewBlock/index.tsx
- @stellar/design-system-website/src/components/PreviewBlock/styles.css
- @stellar/design-system/src/components/Textarea/index.tsx
> Textarea docs + preview

- @stellar/design-system-website/docs/components/inputs/radio-button.mdx
- @stellar/design-system-website/src/componentPreview/radioButtonPreview.tsx
- @stellar/design-system-website/src/components/PreviewBlock/index.tsx
- @stellar/design-system/src/components/RadioButton/index.tsx
> RadioButton docs + preview

- @stellar/design-system-website/docs/components/buttons/button-preset.mdx
- @stellar/design-system-website/docs/components/buttons/icon-button.mdx
- @stellar/design-system-website/src/componentPreview/buttonPresetPreview.tsx
- @stellar/design-system-website/src/componentPreview/iconButtonPreview.tsx
- @stellar/design-system-website/src/components/PreviewBlock/index.tsx
- @stellar/design-system/src/components/ButtonPreset/index.tsx
- @stellar/design-system/src/components/IconButton/index.tsx
- @stellar/design-system/src/components/index.ts
Moved the button preset to its own component for clarity because it was confusing to have them in `IconButton`.
> IconButton and ButtonPreset docs + preview

- @stellar/design-system-website/docs/components/buttons/copy-text.mdx
- @stellar/design-system-website/src/componentPreview/copyTextPreview.tsx
- @stellar/design-system-website/src/components/PreviewBlock/index.tsx
- @stellar/design-system/src/components/ButtonPreset/index.tsx
- @stellar/design-system/src/components/CopyText/index.tsx
- @stellar/design-system/src/components/IconButton/index.tsx
> CopyText docs + preview

- @stellar/design-system-website/docs/components/containers/_category_.json
- @stellar/design-system-website/docs/components/containers/card.mdx
- @stellar/design-system-website/src/componentPreview/cardPreview.tsx
- @stellar/design-system-website/src/components/PreviewBlock/index.tsx
- @stellar/design-system-website/src/components/PreviewBlock/styles.css
- @stellar/design-system/src/components/Card/index.tsx
> Card docs + preview

- @stellar/design-system-website/README.md
- @stellar/design-system-website/docs/get-started/intro.mdx
- @stellar/design-system-website/docusaurus.config.js
- @stellar/design-system-website/package.json
- @stellar/design-system/README.md
- README.md
- yarn.lock
> Updated intro + readme

- @stellar/design-system-website/docs/foundations/colors.mdx
- @stellar/design-system-website/src/components/AssetPreview/styles.css
- @stellar/design-system-website/src/components/ColorPalette/index.tsx
- @stellar/design-system-website/src/components/ColorPalette/styles.css
- @stellar/design-system-website/src/components/ColorPaletteThemeSwitcher/index.tsx
- @stellar/design-system-website/src/components/ColorPaletteThemeSwitcher/styles.css
- @stellar/design-system-website/src/css/custom.css
- @stellar/design-system-website/src/theme/MDXComponents.js
> SDS web: colors page

- @stellar/design-system/src/components/Link/index.tsx
- @stellar/design-system/src/components/Profile/index.tsx
- @stellar/design-system/src/components/ProjectLogo/index.tsx
Updated `Link`, `Profile`, and `ProjectLogo` components to accept custom anchor elements. For example, `Link` in Next.js for client-side routing; otherwise, it would trigger a full page reload.
> Support custom anchor elements

- @stellar/design-system-website/src/componentPreview/textareaPreview.tsx
- @stellar/design-system/src/components/Input/index.tsx
- @stellar/design-system/src/components/Textarea/index.tsx
- @stellar/design-system/src/components/Textarea/styles.scss
- @stellar/design-system/src/components/utils/InputCopyButton.tsx
> Textarea copy text button

- @stellar/design-system-website/src/componentPreview/inputPreview.tsx
- @stellar/design-system-website/src/componentPreview/selectPreview.tsx
- @stellar/design-system-website/src/componentPreview/textareaPreview.tsx
- @stellar/design-system/src/components/Input/index.tsx
- @stellar/design-system/src/components/Label/index.tsx
- @stellar/design-system/src/components/Label/styles.scss
- @stellar/design-system/src/components/Select/index.tsx
- @stellar/design-system/src/components/Textarea/index.tsx
- @stellar/design-system/src/components/ThemeSwitch/index.tsx
- @stellar/design-system/src/components/Tooltip/index.tsx
- @stellar/design-system/src/components/Tooltip/styles.scss
- Added info text tooltip prop to `Label`, `Input`, `Select`, and `Textarea` components.
- `Tooltip` content will correctly switch colors in contrast mode (when showing a dark bubble).
<details>
<summary>Examples</summary>
</details>
>[!NOTE]
>The SDS website doesn't show the correct Tooltip bubble theme when using light mode in the component preview because it's not using a global theme (Docusaurus controls that). It looks fine in the dark mode because that is the default. It should work as expected in projects that use SDS globally.
> Label info text + updated Tooltip colors

- @stellar/design-system-website/src/componentPreview/inputPreview.tsx
- @stellar/design-system-website/src/componentPreview/selectPreview.tsx
- @stellar/design-system-website/src/componentPreview/textareaPreview.tsx
- @stellar/design-system/src/components/Floater/index.tsx
- @stellar/design-system/src/components/Input/index.tsx
- @stellar/design-system/src/components/Label/index.tsx
- @stellar/design-system/src/components/Select/index.tsx
- @stellar/design-system/src/components/Textarea/index.tsx
- @stellar/design-system/src/components/ThemeSwitch/index.tsx
- @stellar/design-system/src/components/Tooltip/index.tsx
Info text (in tooltip)
Info link (opens in new window)
> Label info link + update Tooltip theme setting

- @stellar/design-system/src/components/Textarea/index.tsx
**Summary:**
- making `<Textarea />`'s footer optional otherwise, it'd have an unneeded gap by default
> update <textarea/>'s footer to be conditional

- @stellar/design-system-website/src/componentPreview/notificationPreview.tsx
- @stellar/design-system-website/src/components/PreviewBlock/index.tsx
- @stellar/design-system/src/components/Notification/index.tsx
- @stellar/design-system/src/components/Notification/styles.scss
- Enable `isFilled` option on `<Notification/>` for `success`, `warning`, and `error`
> enable `isFilled` on <Notification/>

- @stellar/design-system/src/components/Floater/styles.scss
- @stellar/design-system/src/components/Input/styles.scss
- @stellar/design-system/src/components/Textarea/index.tsx
- Fix Floater z-index when the tooltip is open (fixes Copy button overlap for Input)
- Fix Input element width to allow shrinking when the Input is small
- Fix Textarea value to allow both value and children (used to have only children)
> UI fixes: floater z-index + input and textarea fixes

- @stellar/design-system/src/components/Toggle/styles.scss
We discovered the Toggle component wasn't able to be tabbed to using the keyboard because the underlying input is set to `display: none`, which is an accessibility issue
This PR works around this by setting height and width to 0. It also adds focus styling
Unfocused:
Focused:
> allow Toggle to be tabbed and add focus styling

- .gitignore
- @stellar/design-system-website/package.json
- @stellar/design-system/package.json
- @stellar/design-system/src/components/Input/index.tsx
- @stellar/design-system/src/components/Label/index.tsx
- @stellar/design-system/src/components/Select/index.tsx
- @stellar/design-system/src/components/Textarea/index.tsx
- Add optional `infoTextIcon` and `infoLinkIcon` props to `Input`, `Select`, and `Textarea` components to allow setting custom icons.
- Bump SDS version to `3.1.1`
> Allow custom icons for info link and text
